//
// DO NOT EDIT THIS FILE.
// Generated using AndroidAnnotations 4.6.0.
// 
// You can create a larger work that contains this file and distribute that work under terms of your choice.
//

package ru.orangesoftware.financisto.bus;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class GreenRobotBus_
    extends GreenRobotBus
{
    private Context context_;
    private static GreenRobotBus_ instance_;

    private GreenRobotBus_(Context context) {
        context_ = context;
    }

    public static GreenRobotBus_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new GreenRobotBus_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }
}
