//
// DO NOT EDIT THIS FILE.
// Generated using AndroidAnnotations 4.6.0.
// 
// You can create a larger work that contains this file and distribute that work under terms of your choice.
//

package ru.orangesoftware.financisto.app;

import ru.orangesoftware.financisto.bus.GreenRobotBus_;

public final class FinancistoApp_
    extends FinancistoApp
{
    private static FinancistoApp INSTANCE_;

    public static FinancistoApp getInstance() {
        return INSTANCE_;
    }

    /**
     * Visible for testing purposes
     */
    public static void setForTesting(FinancistoApp application) {
        INSTANCE_ = application;
    }

    @Override
    public void onCreate() {
        INSTANCE_ = this;
        init_();
        super.onCreate();
    }

    private void init_() {
        this.bus = GreenRobotBus_.getInstance_(this);
        init();
    }
}
