//
// DO NOT EDIT THIS FILE.
// Generated using AndroidAnnotations 4.6.0.
// 
// You can create a larger work that contains this file and distribute that work under terms of your choice.
//

package ru.orangesoftware.financisto.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import androidx.core.app.ActivityCompat;
import androidx.fragment.app.Fragment;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.builder.PostActivityStarter;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;
import ru.orangesoftware.financisto.R;

public final class RequestPermissionActivity_
    extends RequestPermissionActivity
    implements HasViews, OnViewChangedListener
{
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String REQUESTED_PERMISSION_EXTRA = "requestedPermission";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(R.layout.activity_request_permissions);
    }

    @Override
    public<T extends View> T internalFindViewById(int id) {
        return ((T) this.findViewById(id));
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static RequestPermissionActivity_.IntentBuilder_ intent(Context context) {
        return new RequestPermissionActivity_.IntentBuilder_(context);
    }

    public static RequestPermissionActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new RequestPermissionActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        this.toggleWriteStorageWrap = hasViews.internalFindViewById(R.id.toggleWriteStorageWrap);
        this.toggleWriteStorage = hasViews.internalFindViewById(R.id.toggleWriteStorage);
        if (this.toggleWriteStorage!= null) {
            this.toggleWriteStorage.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    RequestPermissionActivity_.this.onGrantWriteStorage();
                }
            }
            );
        }
        initViews();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(REQUESTED_PERMISSION_EXTRA)) {
                this.requestedPermission = extras_.getString(REQUESTED_PERMISSION_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<RequestPermissionActivity_.IntentBuilder_>
    {
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, RequestPermissionActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            super(fragment.getActivity(), RequestPermissionActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public PostActivityStarter startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (context instanceof Activity) {
                    Activity activity = ((Activity) context);
                    ActivityCompat.startActivityForResult(activity, intent, requestCode, lastOptions);
                } else {
                    context.startActivity(intent);
                }
            }
            return new PostActivityStarter(context);
        }

        /**
         * @param requestedPermission
         *     the value for this extra
         * @return
         *     the IntentBuilder to chain calls
         */
        public RequestPermissionActivity_.IntentBuilder_ requestedPermission(String requestedPermission) {
            return super.extra(REQUESTED_PERMISSION_EXTRA, requestedPermission);
        }
    }
}
