//
// DO NOT EDIT THIS FILE.
// Generated using AndroidAnnotations 4.6.0.
// 
// You can create a larger work that contains this file and distribute that work under terms of your choice.
//

package ru.orangesoftware.financisto.widget;

import java.util.ArrayList;
import android.content.Context;
import android.os.Bundle;
import android.os.Vibrator;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;
import ru.orangesoftware.financisto.R;

public final class CalculatorInput_
    extends ru.orangesoftware.financisto.widget.CalculatorInput
    implements HasViews, OnViewChangedListener
{
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;
    public final static String AMOUNT_ARG = "amount";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public<T extends View> T internalFindViewById(int id) {
        return ((T)((contentView_ == null)?null:contentView_.findViewById(id)));
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(R.layout.calculator, container, false);
        }
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        contentView_ = null;
        tvResult = null;
        tvOp = null;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectFragmentArguments_();
        this.vibrator = ((Vibrator) getActivity().getSystemService(Context.VIBRATOR_SERVICE));
        init();
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static CalculatorInput_.FragmentBuilder_ builder() {
        return new CalculatorInput_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        this.tvResult = hasViews.internalFindViewById(R.id.result);
        this.tvOp = hasViews.internalFindViewById(R.id.op);
        ArrayList<Button> list_buttons = new ArrayList<Button>();
        Button view_b0 = hasViews.internalFindViewById(R.id.b0);
        Button view_b1 = hasViews.internalFindViewById(R.id.b1);
        Button view_b2 = hasViews.internalFindViewById(R.id.b2);
        Button view_b3 = hasViews.internalFindViewById(R.id.b3);
        Button view_b4 = hasViews.internalFindViewById(R.id.b4);
        Button view_b5 = hasViews.internalFindViewById(R.id.b5);
        Button view_b6 = hasViews.internalFindViewById(R.id.b6);
        Button view_b7 = hasViews.internalFindViewById(R.id.b7);
        Button view_b8 = hasViews.internalFindViewById(R.id.b8);
        Button view_b9 = hasViews.internalFindViewById(R.id.b9);
        Button view_bAdd = hasViews.internalFindViewById(R.id.bAdd);
        Button view_bSubtract = hasViews.internalFindViewById(R.id.bSubtract);
        Button view_bDivide = hasViews.internalFindViewById(R.id.bDivide);
        Button view_bMultiply = hasViews.internalFindViewById(R.id.bMultiply);
        Button view_bPercent = hasViews.internalFindViewById(R.id.bPercent);
        Button view_bPlusMinus = hasViews.internalFindViewById(R.id.bPlusMinus);
        Button view_bDot = hasViews.internalFindViewById(R.id.bDot);
        Button view_bResult = hasViews.internalFindViewById(R.id.bResult);
        Button view_bClear = hasViews.internalFindViewById(R.id.bClear);
        Button view_bDelete = hasViews.internalFindViewById(R.id.bDelete);
        View view_bOK = hasViews.internalFindViewById(R.id.bOK);
        View view_bCancel = hasViews.internalFindViewById(R.id.bCancel);

        if (view_b0 != null) {
            list_buttons.add(view_b0);
            view_b0 .setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_b1 != null) {
            list_buttons.add(view_b1);
            view_b1 .setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_b2 != null) {
            list_buttons.add(view_b2);
            view_b2 .setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_b3 != null) {
            list_buttons.add(view_b3);
            view_b3 .setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_b4 != null) {
            list_buttons.add(view_b4);
            view_b4 .setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_b5 != null) {
            list_buttons.add(view_b5);
            view_b5 .setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_b6 != null) {
            list_buttons.add(view_b6);
            view_b6 .setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_b7 != null) {
            list_buttons.add(view_b7);
            view_b7 .setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_b8 != null) {
            list_buttons.add(view_b8);
            view_b8 .setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_b9 != null) {
            list_buttons.add(view_b9);
            view_b9 .setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_bAdd!= null) {
            list_buttons.add(view_bAdd);
            view_bAdd.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_bSubtract!= null) {
            list_buttons.add(view_bSubtract);
            view_bSubtract.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_bDivide!= null) {
            list_buttons.add(view_bDivide);
            view_bDivide.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_bMultiply!= null) {
            list_buttons.add(view_bMultiply);
            view_bMultiply.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_bPercent!= null) {
            list_buttons.add(view_bPercent);
            view_bPercent.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_bPlusMinus!= null) {
            list_buttons.add(view_bPlusMinus);
            view_bPlusMinus.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_bDot!= null) {
            list_buttons.add(view_bDot);
            view_bDot.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_bResult!= null) {
            list_buttons.add(view_bResult);
            view_bResult.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_bClear!= null) {
            list_buttons.add(view_bClear);
            view_bClear.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_bDelete!= null) {
            list_buttons.add(view_bDelete);
            view_bDelete.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onButtonClick(view);
                }
            }
            );
        }
        if (view_bOK!= null) {
            view_bOK.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onOk();
                }
            }
            );
        }
        if (view_bCancel!= null) {
            view_bCancel.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    CalculatorInput_.this.onCancel();
                }
            }
            );
        }
        this.buttons = list_buttons;
        initUi();
    }

    private void injectFragmentArguments_() {
        Bundle args_ = getArguments();
        if (args_!= null) {
            if (args_.containsKey(AMOUNT_ARG)) {
                this.amount = args_.getString(AMOUNT_ARG);
            }
        }
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<CalculatorInput_.FragmentBuilder_, ru.orangesoftware.financisto.widget.CalculatorInput>
    {

        @Override
        public ru.orangesoftware.financisto.widget.CalculatorInput build() {
            CalculatorInput_ fragment_ = new CalculatorInput_();
            fragment_.setArguments(args);
            return fragment_;
        }

        /**
         * @param amount
         *     value for this Fragment argument
         * @return
         *     the FragmentBuilder to chain calls
         */
        public CalculatorInput_.FragmentBuilder_ amount(String amount) {
            args.putString(AMOUNT_ARG, amount);
            return this;
        }
    }
}
